name: DaKa

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: '45 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *'

jobs:
  DaKa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install pillow
      - name: upload
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT2: ${{ secrets.ACC }}
          PASSWORD2: ${{ secrets.PAS }}
        run: |
          python3 ./daka.py ${ACCOUNT} ${PASSWORD}
          python3 ./daka.py ${ACCOUNT2} ${PASSWORD2}
